name: active_storage
description: Send files to a Rails Active Storage backend using direct upload
version: 1.1.0
homepage: https://www.algonauti.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.6
